### ISSUE TITLE
Restore window to "correct" workspace with custom name

### ISSUE THREAD

**Issue by borderomm** [vrde/i3-quiet#6]
I have custom names for my workspaces. For example:
set $ws1 "1:"

When toggling a window from my $ws1, from quiet mode back to normal, the script restores it in a completely new workspace called "1", instead of "1:"

**Comment by maxdevjs** [comment]
Hello.

@vrde first of all, your project inspired me to start a version of it in `shell scripting`. I had this same issue: when the window is the only one in the original workspace, the original workspace ceases to exist when the window leaves it. 

https://github.com/vrde/i3-quiet/blob/ea1f4b576aa0d8b903a8b53fdf8d509b626ae318/quiet-cmd.py#L54
this line saves the `number` of the original workspace in `workspace_zen`, but the `name` is needed to actually restore it and not to create a new, different, one.

Here
https://github.com/vrde/i3-quiet/blob/ea1f4b576aa0d8b903a8b53fdf8d509b626ae318/quiet-cmd.py#L49
the code then ends up retrieving the `number` of the original desktop, not the `name`.

I save the original workspace name

https://github.com/maxdevjs/i3-focus.sh/blob/8fe46b2c88dc64439da48b7a2e931d36d0dfdc70/i3wm-focus#L51

and then restore it. It works with my workspace names (and yes, I have  myself in one of them). Hopefully it is enough to solve our common issue.

(I do not send a PR because I did not test your code to affirm anything).

**Comment by vrde** [comment]
@maxdevjs thanks, will give it a try this weekend :)

(Happy it inspired you to create a bash version, great job!)

**Comment by tcaxle** [comment]
I use a dynamic workspace renaming script [dynamic workspace renaming script](https://github.com/cboddy/i3-workspace-names-daemon) so have found no readily available way to restore the window to the correct workspace without using a file to store the original workspace as a JSON object as part of the ```enable_zen_mode``` function.

Have submitted a PR.
